### ISSUE TITLE
'git-pw patch list --delegate foo' fails

### ISSUE THREAD

**Issue by dzickusrh** [getpatchwork/git-pw#10]
Running the above command results in:

```
[dzickus@dzickus-laptop rhel7]$ git-pw --debug patch list --delegate foo
2018-03-13 11:01:46,012 - git_pw.patch - INFO - List patches:
states=under-review,new, submitters=, delegates=foo, archived=False
2018-03-13 11:01:46,022 - git_pw.config - DEBUG - Retrieved 'server' setting
from git-config
2018-03-13 11:01:46,022 - git_pw.config - DEBUG - Retrieved 'server' setting
from cache
Traceback (most recent call last):
  File "/home/dzickus/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dzickus/lib/python/git_pw/patch.py", line 216, in list_cmd
    users = api.index('users', {'q': delg})
  File "/home/dzickus/lib/python/git_pw/api.py", line 172, in index
    params.append(('project', _get_project()))
AttributeError: 'dict' object has no attribute 'append'
```

**Comment by stephenfin** [comment]
I'm seeing the same think when filtering series by submitter:

```
$ git pw series list --submitter vkabatov@redhat.com
Traceback (most recent call last):
  File "/home/sfinucan/.local/bin/git-pw", line 11, in <module>
    sys.exit(cli())
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sfinucan/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sfinucan/.local/lib/python2.7/site-packages/git_pw/series.py", line 112, in list_cmd
    people = api.index('people', {'q': subm})
  File "/home/sfinucan/.local/lib/python2.7/site-packages/git_pw/api.py", line 172, in index
    params.append(('project', _get_project()))
AttributeError: 'dict' object has no attribute 'append'
```
