### ISSUE TITLE
python integration not working

### ISSUE THREAD

**Issue by wizardofoz123** [getpatchwork/git-pw#11]
Hi,

I'm trying to run equivalent of following command:
$ git-pw patch list --limit 5

by using following Python code:

```
from git_pw import patch
print patch.list_cmd((u'under-review', u'new'),(),(), False, 5, None, '-date', None)
```
The parameters I'm passing to list_cmd should be OK. I've instrumented git_pw/patch.py to have them printed before running $ git-pw patch list --limit 5.

Unfortunately, my Python example doesn't work:

```
Traceback (most recent call last):
  File "./testcase.py", line 3, in <module>
    print patch.list_cmd((u'under-review', u'new'),(),(), False, 5, None, '-date', None)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
TypeError: main() takes at most 5 arguments (9 given)
```

It looks like the interface is broken, could you please fix it?

**Comment by wizardofoz123** [comment]
OK, so it appears the API works a little different than I thought. It comes down to filling-in config object and using .api call:

```
from git_pw import patch
from git_pw import config

c = config.Config()
c.server = 'http://domain.server,cin/'
c.project= 'project'
c.username = 'user'
c.token = 'ffffffffffffffffffffffffffffffffffffffff'

patch.api.CONF = c
xpatch = patch.api.detail('patches', 101010)
print xpatch
```
So this is most likely not an issue.
