### ISSUE TITLE
Issue with unquoted csv output format

### ISSUE THREAD

**Issue by john-mcnamara-intel** [getpatchwork/git-pw#46]
Some output fields from `git-pw` contain commas which break the CSVoutput.

For example consider a query like this against the [DPDK Patchwork](http://patches.dpdk.org/project/dpdk/list/):

    $ git-pw patch list RFC --column ID --column Name --limit 4
    +-------+-----------------------------------------------------------------+
    |    ID | Name                                                            |
    |-------+-----------------------------------------------------------------|
    | 59107 | [RFC] kni: properly translate pa2va for cloned mbuf             |
    | 59106 | [RFC,v3,4/4] app/testpmd: show the Rx/Tx burst mode description |
    | 59105 | [RFC,v3,3/4] net/ice: support to get the Rx/Tx burst mode       |
    | 59104 | [RFC,v3,2/4] net/i40e: support to get the Rx/Tx burst mode      |
    +-------+-----------------------------------------------------------------+

If you then add the format csv option you get this:

    $ git-pw patch list RFC --column ID --column Name --limit 4 -f csv
    ID,Name
    59107,[RFC] kni: properly translate pa2va for cloned mbuf
    59106,[RFC,v3,4/4] app/testpmd: show the Rx/Tx burst mode description
    59105,[RFC,v3,3/4] net/ice: support to get the Rx/Tx burst mode
    59104,[RFC,v3,2/4] net/i40e: support to get the Rx/Tx burst mode

The commas in the Name fields means that there are too many CSV fields. I'd guess that they should be quoted:

    $ git-pw patch list RFC --column ID --column Name --limit 4 -f csv
    ID,Name
    59107,"[RFC] kni: properly translate pa2va for cloned mbuf"
    59106,"[RFC,v3,4/4] app/testpmd: show the Rx/Tx burst mode description"
    59105,"[RFC,v3,3/4] net/ice: support to get the Rx/Tx burst mode"
    59104,"[RFC,v3,2/4] net/i40e: support to get the Rx/Tx burst mode"

Version is 1.6.0 from the current HEAD:

    $ git-pw --version
    git-pw, version 1.6.0

**Comment by john-mcnamara-intel** [comment]
> csv.py

Sorry for being unclear, I meant the standard lib csv.py: https://docs.python.org/3/library/csv.html (although it may not fit in with your code).

**Comment by stephenfin** [comment]
@john-mcnamara-intel I should have this fixed on master now. Can you test this and let me know if it fixes things for you? If so, I'll cut a new release.

Hint: to test locally without wiping your install:

```
# cd to project (DPDK?) directory
$ virtualenv .venv
$ source .venv/bin/activate
$ pip install https://github.com/getpatchwork/git-pw/archive/master.zip
# ... run your tests
$ deactivate
$ rm -rf .venv
```

**Comment by john-mcnamara-intel** [comment]
With a full install in Python 2 the changes on HEAD give the following error:

```
$ git-pw patch list RFC --column ID --column Name --column Date --limit 4 -f csv
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
    utils.echo_via_pager(output, headers, fmt=fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 138, in echo_via_pager
    output = _tabulate(output, headers, fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 73, in _tabulate
    result = StringIO()
NameError: global name 'StringIO' is not defined
```
Since the import probably should be:
```python
if sys.version_info < (3, 0):
    from StringIO import StringIO  # noqa
else:
    from io import StringIO  # noqa
```
However, that in turn throws another issue:

```
$ git-pw patch list RFC --column ID --column Name --column Date --limit 4 -f csv
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
    utils.echo_via_pager(output, headers, fmt=fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 138, in echo_via_pager
    output = _tabulate(output, headers, fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 77, in _tabulate
    writer.writerow(_text(x if x is not None else '') for x in item)
_csv.Error: sequence expected
```

**Comment by stephenfin** [comment]
Let's try again. Can you check the latest master?

**Comment by john-mcnamara-intel** [comment]
Thanks. There is still an issue in Python 2.7:

```
$ git-pw patch list RFC --column ID --column Name --column Date --limit 4 -f csv
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
    utils.echo_via_pager(output, headers, fmt=fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 130, in echo_via_pager
    output = _tabulate(output, headers, fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 66, in _tabulate
    writer.writerow([six.ensure_str(h) for h in headers])
AttributeError: 'module' object has no attribute 'ensure_str'
````

**Comment by stephenfin** [comment]
That's because you've got an old version of `six` installed. You need at least [1.12](https://github.com/benjaminp/six/commit/db3d0d678b422614d5de0f9ed76a2112a28c7b19). If you're using a virtualenv, can you recreate it? If you're not, can you install a newer version of `six`?

**Comment by john-mcnamara-intel** [comment]
> That's because you've got an old version of six installed. You need at least 1.12.

You are right.  Sorry about that. I thought that would be picked up from requirements.txt.


> If you're using a virtualenv, can you recreate it?

I'm not using virtualenv. I'm installing git-pw directly into the system:

```
$ sudo python setup.py install
```
>  If you're not, can you install a newer version of six?

I've updated any versions that needed:
```
$ pip2 freeze | egrep "click|requests|tabulate|arrow|six"
arrow==0.10.0
click==6.6
requests==2.19.1
six==1.12.0
tabulate==0.8.3
```
The six issue is fixed. However, there is still an issue:

```
$ git-pw patch list RFC --column ID --column Name --column Date --limit 4 -f csv
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
    utils.echo_via_pager(output, headers, fmt=fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 130, in echo_via_pager
    output = _tabulate(output, headers, fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 69, in _tabulate
    six.ensure_str(x if x is not None else '') for x in item])
  File "/usr/lib/python2.7/site-packages/six.py", line 884, in ensure_str
    raise TypeError("not expecting type '%s'" % type(s))
TypeError: not expecting type '<type 'int'>'
```

**Comment by stephenfin** [comment]
Third times the charm? :see_no_evil: New version pushed that handles ints too.

**Comment by john-mcnamara-intel** [comment]
Sucess!

```
$ git-pw patch list RFC --column ID --column Name --column Date --limit 4 -f csv
"ID","Name","Date"
"59272","2 days ago","[RFC,v3] net/i40e: enable multi-queue Rx interrupt for VF"
"59107","7 days ago","[RFC] kni: properly translate pa2va for cloned mbuf"
"59106","7 days ago","[RFC,v3,4/4] app/testpmd: show the Rx/Tx burst mode description"
"59105","7 days ago","[RFC,v3,3/4] net/ice: support to get the Rx/Tx burst mode"
```

Thanks for the fix and your patience.

However, I'm now seeing a Unicode issue in another case.

Here is a dump from the DPDK patchwork which works:

```
$ git-pw patch list "bulk" --column ID --column Submitter
+-------+------------------------------------------+
|    ID | Submitter                                |
|-------+------------------------------------------|
| 59113 | Morten BrÃ¸rup (mb@smartsharesystems.com) |
+-------+------------------------------------------+
```

However, with the CSV output it throws an exception

```
$ git-pw patch list "bulk" --column ID --column Submitter -f csv
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/api.py", line 303, in new_func
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/patch.py", line 265, in list_cmd
    utils.echo_via_pager(output, headers, fmt=fmt)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 155, in echo_via_pager
    _echo_via_pager('less', output)
  File "/usr/lib/python2.7/site-packages/git_pw/utils.py", line 113, in _echo_via_pager
    c.stdin.write(line.encode(encoding, 'replace'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
"ID","Submitter"
"59113","Morten Br
```

**Comment by stephenfin** [comment]
Tracked in #49. Let me know if the fix I've pushed for that does the trick. Unicode is hard :cold_sweat:
