### ISSUE TITLE
packaging for Gentoo Linux

### ISSUE THREAD

**Issue by dlan17** [getpatchwork/git-pw#58]
hello, I'm trying to pack this great tool for Gentoo Linux, while face a build err.
It fail to find version info from PKG-INFO or METADATA (which both files not found)

```
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-vcs/git-pw-2.0.0/work/git-pw-2.0.0 ...
 * python3_8: running distutils-r1_run_phase distutils-r1_python_compile
python3.8 setup.py build -j 30
/usr/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/lib/python3.8/site-packages/pbr/util.py", line 271, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/lib/python3.8/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/lib/python3.8/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/lib/python3.8/site-packages/pbr/hooks/metadata.py", line 25, in hook
    self.config['version'] = packaging.get_version(
  File "/usr/lib/python3.8/site-packages/pbr/packaging.py", line 874, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name git-pw was given, but was not able to be found.
error in setup command: Error parsing /var/tmp/portage/dev-vcs/git-pw-2.0.0/work/git-pw-2.0.0/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name git-pw was given, but was not able to be found.
 * ERROR: dev-vcs/git-pw-2.0.0::local failed (compile phase):
 *   (no error message)
```

**Comment by stephenfin** [comment]
I'm not familiar with Gentoo packaging, however, the error message seems clear. I suspect you're using the tarballs from GitHub when what you actually want is an sdist tarball. You can build one of those with `python setup.py build_sdist`.
