### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1005-1007: ordinal not in range(128)

### ISSUE THREAD

**Issue by borkmann** [getpatchwork/git-pw#6]
While applying a series from patchwork, I ran into the following error:

```
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/git_pw/series.py", line 41, in apply_cmd
    p.communicate(mbox)
  File "/usr/lib64/python2.7/subprocess.py", line 465, in communicate
    self.stdin.write(input)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1005-1007: ordinal not in range(128)
```

**Comment by borkmann** [comment]
Same test with python3:
```
Traceback (most recent call last):
  File "/usr/bin/git-pw", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/git_pw/series.py", line 41, in apply_cmd
    p.communicate(mbox)
  File "/usr/lib64/python3.5/subprocess.py", line 1057, in communicate
    self._stdin_write(input)
  File "/usr/lib64/python3.5/subprocess.py", line 1012, in _stdin_write
    self.stdin.write(input)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by stephenfin** [comment]
@borkmann Any chance you could point to the patch in question (assuming it's on a public Patchwork instance)?

**Comment by borkmann** [comment]
@stephenfin Yes, the test case would be this series which seems to have non-ascii chars in the commit log; so I worked around it for the time being by applying by hand instead of using git-pw: http://patchwork.ozlabs.org/project/netdev/list/?series=17373&state=*

**Comment by borkmann** [comment]
fyi, looks like the failure with python3 is a different one; I was hitting it as well with patches that git-pw applies just fine under python2.7.

**Comment by stephenfin** [comment]
@borkmann Any chance you could test the patch on the `bug/6` branch. You can temporarily install this version like so:

```
cd $DIRECTORY_OF_NETDEV_SOURCE
virtualenv .venv
source .venv/bin/activate
pip install git+git://github.com/getpatchwork/git-pw.git@bug/6
git-pw series apply 17373
```

Once done, you can simply run `deactivate` and remove the `.venv` directory.

**Comment by borkmann** [comment]
Awesome, that works fine! Thanks a lot for your help!

**Comment by stephenfin** [comment]
This is include in *1.1.0*.
